.golangci.yml

test PR to see if timeout is simply due to dependency download taking "too" long

fix: timeout might be due to dependency downloads

---

helm/chart/templates/role.yaml
internal/server/engine.go
pkg/instance/docs.go
pkg/instance/handler.go
pkg/instance/kubernetes.go
pkg/instance/service.go
pkg/instance/ttlDestroyConsumer_test.go
scripts/restart.sh
swagger/swagger.yaml

This PR allows us to restart instances
The following limitations exists
* Restart only works for deployments, not statefulsets and others
* The deployment needs to have the "app.kubernetes.io/instance" label
* Currently we can only restart whoami-go and dhis2-core instances (not pgadmin or postgresql databases, one is lacking the required label and the other is controlled by a statefulset and not a deployment)

feat: restart instances

---

pkg/instance/ttlDestroyConsumer.go

as re-consuming them will never be successful

fix: nack TTL messages containing invalid JSON

---

pkg/instance/helmfile.go

* shorter variable names https://go.dev/doc/effective_go#names
* only export what is used outside of the declaring package for example `StackParameters`
* declare vars as close to their usage as possible for example `cmd`. Improves readability and potentially saves work in case of an errors between declaration and use.
* only use a method if the receiver is actually used. The receiver is syntactic sugar. Think of it as the first parameter.
* fix loadStackParameters as it did not return an error in case of an error in `os.ReadFile(path)`
* return nil for pointers in case of error like
```go
if err != nil {
return nil, err
}
```
* slices and maps are already using pointer semantics meaning the underlying array/map is shared. We should not use `*[]string` or `*map[string]string`. Example …

chore: adopt more go idioms in helmfile

---

pkg/instance/helmfile.go
pkg/instance/kubernetes.go
pkg/instance/service.go

* move kubernetes/helmfile interfaces to consumer
* add context to triple return in interface distinguishing multiple parameters of the same type

chore: move kubernetes/helmfile interfaces to consumer

---

cmd/serve/main.go
pkg/stack/loader.go

stack templates can have many configurations/permutations that we should test. parsing stack templates is easier to test in isolation by
separating it from the CRUD operations.
This change highlights that we can merge the 2 DB transactions Create/Save into a single one. We might even be able to only use 1 DB transaction to create a stack with its required/optional parameters. This prevents stacks from potentially being in an illegal state in case any of the current 4 transactions fails.
Parsing the stacks before any crud operation also lets us fail
starting the instance manager early. So no stack with a template that
cannot be parsed will even be created.

chore: separate parsing from CRUD

---

pkg/instance/handler.go
pkg/instance/service.go
pkg/instance/ttlDestroyConsumer_test.go

* we already have the instance so no need to `s.FindById(id)` again in the instance service
* updating the scale object already returns it so we do not need to get it again

chore: remove redundant operations in restart

---

cmd/serve/main.go
pkg/instance/kubernetes.go
pkg/instance/service.go

The instance service is doing too many low level kubernetes things IMHO 😄 The kubernetes service can be our higher level client to kubernetes APIs we use. Practically this means that I would try to have only kubernetes.go depend on `k8s.io` things.
Separating these changes from the pausing feature will make those changes easier to read.

chore: move kubernetes domain into kube service

---

pkg/instance/docs.go
pkg/instance/handler.go
pkg/instance/kubernetes.go
pkg/instance/service.go
pkg/instance/ttlDestroyConsumer_test.go
scripts/restart.sh
stacks/dhis2-core/helmfile.yaml
stacks/dhis2-db/helmfile.yaml
stacks/dhis2/helmfile.yaml
stacks/im-job-runner/helmfile.yaml
stacks/pgadmin/helmfile.yaml
stacks/whoami-go/helmfile.yaml
swagger/sdk/client/operations/restart_instance_parameters.go
swagger/swagger.yaml

at least all the resources we have control over. the pgAdmin helm chart only allows us to label pods and not deployments for example.
* return an error when trying to stream logs using a type selector that does not exist in the instances stack. Example `no pod found using the selector: "im-id=52,im-type=dff"`

chore: consistently label all stack resources

---

scripts/deploy-dhis2.sh
scripts/update-dhis2.sh
stacks/dhis2/helmfile.yaml

Adding an option to install Redis in the monolith `dhis2` stack, so that it can be used as a [data store](https://docs.dhis2.org/en/manage/performing-system-administration/dhis-core-version-master/installation.html#install_cluster_configuration_redis) for system tasks (and other things like user sessions, system settings, etc) instead of storing them in-memory.
And substituting `PGADMIN_INSTALL` for `INSTALL_PGADMIN`.

feat: Add optional Redis release to dhis2 stack

---

pkg/instance/helmfile.go
pkg/stack/loader.go
scripts/deploy-whoami-ttl.sh
stacks/dhis2-core/helmfile.yaml
stacks/dhis2-db/helmfile.yaml
stacks/dhis2/helmfile.yaml
stacks/im-job-runner/helmfile.yaml
stacks/pgadmin/helmfile.yaml
stacks/whoami-go/helmfile.yaml

This PR adds a creation timestamp label to each of our stack pods
The actual label is add in helmfile.go
In the loader it's marked as a system parameter
The helmfile.yaml in each stack is updated to include the label
And finally a new user script is added so this can easily be tried

chore: label stack pods with creation timestamp

---

scripts/stack_tests.sh

@radnov and I have discussed the need for some automatic removal of leftover instances in regards to failing stack tests.
Ideally the tests shouldn't fail but we need more experience to adjust the thresholds so they don't.
The downside of this PR is that we might remove the evidence but on the other hand, if the problem persists, the tests could be ran again locally.

chore: cleanup any lingering instances

---

pkg/instance/kubernetes.go

Previously we were restarting instances by scaling them to 0 and then back to whatever number of replicas they had before. The drawback of this method is that it comes with a significant amount of downtime.
This PR updates the "kubectl.kubernetes.io/restartedAt" annotation with the current time and thereby triggers an update in the same way as it would be done using `kubectl rollout restart`.

feat: restart without downtime

---

pkg/instance/repository.go

If a user don't have access to any instances the endpoint /instances simply returns null which IMHO isn't very pretty. This PR will ensure an empty array is returned instead.

chore: return an empty array rather than null

---

skaffold.yaml

Previously we've been installing the roles, required by IM to deploy instances into namespaces, when installing IM itself. It was done within the chart deploying IM itself. This ins't ideal because by doing so we can't easily create or remove namespaces.
This PR only updates the skaffold file by created two profiles, dev and prod, which will be used to deploy im-group into the various namespaces used for production and none production. It doesn't actually use the new profiles.
In the future the we'll delete the [role file](https://github.com/dhis2-sre/im-manager/blob/master/helm/chart/templates/role.yaml) but for now I'll leave it in there since I'm not entirely sure how we'll go about this in the pipeline.
Deploying with a profile is done by running `skaffold dev -p name-of-the-profile`. …

use im-group

---

skaffold.yaml

When a DB is not yet ready while a service is, the service exits with a non zero exit code. This causes 'skaffold dev' to exit and cleanup resources. [Configure skaffold](https://skaffold.dev/docs/references/yaml/#deploy-tolerateFailuresUntilDeadline) to allow restarts within the `statusCheckDeadlineSeconds` as this is a normal occurrence, which is fixed by restarts.
`tolerateFailuresUntilDeadline` is only available in a later config version where helm `artifactOverrides` and `imageStrategy` don't exist any longer https://skaffold.dev/docs/deployers/helm/#configuring-your-helm-project-with-skaffold
The downside is that it will take longer to exit from an unrecoverable error. Namely `statusCheckDeadlineSeconds` or however long it is that a dev sees this and terminates skaffold.

fix: allow im service restarts within skaffold deadline

---

pkg/database/handler.go
pkg/user/docs.go
pkg/user/handler.go
pkg/user/repository.go
pkg/user/router.go
pkg/user/service.go
scripts/users/delete.sh
swagger/swagger.yaml

This PR adds an admin user endpoint `DELETE /users/{id}` for deleting users by their id.
I've added an [extra check to not allow the user to delete themself](https://github.com/dhis2-sre/im-manager/pull/257/files#diff-ca91d4575c0561bc512e314d455708400a1e715c5c98a109cd79960b29ee8a3aR307-R311), which I did by mistake while testing and thought it might be nice to have. Not completely sure if it's okay to have it in the handler, though. Let me know what you think. 👍

feat: implement deleting users by their id

---

.github/workflows/dependabot.yaml

As described in #285, recent dependency updates are causing problems with linting and building the app. This PR temporary disables the workflow that merges dependabot PRs by commenting out the `on: pull_request` trigger and changing it to manual trigger.

chore: temporary disable dependabot merge workflow

---

pkg/user/docs.go
pkg/user/handler.go
swagger/swagger.yaml

While working on the front end I wanted to see what kind of payload is used when updating a user. Therefor I went to https://api.im.dev.test.c.dhis2.org/docs#operation/updateUser only to find that it was documented.
I also unexported the request struct since there's currently no need to export it.

chore: document update user request and unexport it

---

scripts/databases/seed.sh

As we start to get users actually using the Instance Manager, we need to have the databases frequently seeded and kept in sync. This PR improves the databases `seed.sh` to allow for easier seeding of the most frequently used databases, as well as provide an option for specifying DB versions manually.
The seed script will now have two options for usage:
* With only a group name provided `./seed whoami` - this will default to seeding databases for all DHIS2 versions (taken from the [stable.json](https://releases.dhis2.org/v1/versions/stable.json) file) for the current and 2 previous versions, without hotfixes, as we don't publish specific database versions for hotfixes.
* With group name and explicit database versions provided `./seed whoami 2.40 2.39`.

refactor: improve databases seed script

---

pkg/integration/handler.go

Add `IMAGE_PULL_POLICY` option to integrations endpoint. As described in [DEVOPS-261](https://dhis2.atlassian.net/browse/DEVOPS-261) the whole integrations logic should be refactored and moved out of the handler, but in a separate PR.

chore: add image pull policy integration

---

pkg/group/docs.go
pkg/group/handler.go
pkg/group/repository.go
scripts/users/createGroup.sh
swagger/swagger.yaml

Turns out that if the Deployable bool field is `false`, the validation from the "required" tag will fail
```
Error #01: Key: 'CreateGroupRequest.Deployable' Error:Field validation for 'Deployable' failed on the 'required' tag
```
as it's considered the zero-value for bools. In our case both `true` and `false` are valid, so there's no need to use the "required" tag.
I've also handled the duplicated key error when creating a `group`, but I'm not sure how to distinguish between duplicated `Hostname` and `Name`. Any ideas?

fix: remove "required" binding from Deployable bool field

---

pkg/model/stack.go
pkg/stack/loader_test.go
pkg/stack/stack.go
stacks/pgadmin/helmfile.yaml

* Declare the metadata of stacks in Go. That is the first step in transitioning the metadata we currently have as comments in a stack's helmfile.
We are not yet using the Go stack definitions only putting them in place. We test that the static information in Go matches the one we parse in the stack's helmfile to ensure they are in sync (parameters, values, consumed or not).
* remove unused parameter from stacks/pgadmin/helmfile.yaml `DATABASE_PASSWORD` was declared as consumed but was not actually consumed.
* make Stack.parameters a `map[string]StackParameter` (ignored by Gorm) while still keeping a `[]StackParameter` field to be persisted by Gorm. This is so that parameters match what we need in the end which is a map. This makes processing the parameters easier. The compiler will also …

chore: declare stacks in Go DEVOPS-223

---

pkg/database/service.go
pkg/instance/service.go
pkg/model/stack.go
pkg/stack/loader.go
pkg/stack/loader_test.go
pkg/stack/repository.go
pkg/stack/stack.go
pkg/stack/stack_integration_test.go
swagger/swagger.yaml

create map of parameter names to parameters as in the end we need a map of name/value pairs to set the environment variables for the stack's helmfile. Use Gorm hooks to transform the map to a slice as it cannot persist the parameters otherwise.

chore: create map of parameter names to parameters DEVOPS-223

---

pkg/stack/loader.go
pkg/stack/loader_test.go
pkg/stack/stack.go

to prepare using them in the loader and validating that
* all stacks consumed parameters are provided
* we do not have a cycle in our stack definition

chore: declare all stacks DEVOPS-223

---

pkg/model/stack.go
pkg/stack/loader.go
pkg/stack/stack.go
pkg/stack/stack_test.go
swagger/swagger.yaml

validate
* all consumed parameters have exactly one provider
* a stack requires every stack only once
* every required stack actually provides at least one consumed parameter
* a consumed parameter cannot be provided
* validate stacks have no cycle

chore: validate consumed parameters are provided by required stacks DEVOPS-223

---

pkg/instance/service.go
pkg/instance/service_test.go
pkg/model/stack.go
pkg/stack/loader_test.go
pkg/stack/stack.go
pkg/stack/stack_test.go

* stack parameters can define a `Validator` which is a `func (value string) error`. I am not adding an interface like for `Provider`. I don't anticipate us needing any `struct` holding state like a `AWS` client or so that should satisfy this interface. Validators IMHO will mostly be functions. Functions cannot implement an interface in Go which leads to the pattern like the [http/HandlerFunc](https://pkg.go.dev/net/http#HandlerFunc) which makes things more complex. We can go there if needed.
* adapted the minimum parameter validation we had in instance service. New algorithm: collect as many errors as possible by iterating over all instance parameters
* add error if parameter is not part of the instance's stack
* add error if there is a Validator to run that returns an error
* join all …

chore: add parameter validation mechanism DEVOPS-223

---

scripts/users/addUserToGroup.sh
scripts/users/delete.sh
scripts/users/findAllGroups.sh
scripts/users/list.sh
scripts/users/me.sh
scripts/users/update.sh

these might not be all the scripts we should source `auth.sh`. They are at least some I just used to delete my user and add my user to a group after signing up again.
I am also not sure if using type `Admin` is what we always want 🤷🏻 its at least what I need in the flow described above.

chore: source auth.sh in users scripts

---

go.mod
go.sum
pkg/stack/stack.go
pkg/stack/stack_test.go

Cycles in our stack configs we would lead to users sending us linked instances that contain cycles. Such deployments have no order in which they can successfully be deployed.
I picked https://github.com/dominikbraun/graph as it
* does what we need (prevent cycles in our stacks config, topological sort for finding a deployment order of linked instances)
* has no dependencies
* has an easy to use API
* is well tested
Its API might change as its pre 1.0. Some Go projects never reach 1.0 even if they are feature complete. Some due to reluctance to go into a v1/v2/... API versioning 😅 
We could look into implementing this ourselves if we prefer.

chore: validate stack config has no cycles DEVOPS-223

---

cmd/serve/main.go
pkg/instance/handler.go
pkg/instance/helmfile.go
pkg/instance/repository.go
pkg/instance/router.go
pkg/instance/service.go
pkg/model/stack.go
skaffold.yaml
swagger/swagger.yaml

* remove unused dependencies/fields
* remove instance service interface in the instance handler as we do not benefit from it. We do not test the handler in isolation, nor do we have multiple instance service implementations. Its also not 3rd party code we want to isolate our code from. Only add an interface for any of the above reasons.
* only pass in the needed config instead of the entire config struct

chore: make instance handler testable

---

go.mod
go.sum
pkg/instance/helmfile.go
pkg/instance/instance_integration_test.go
pkg/instance/kubernetes.go
pkg/instance/service.go
pkg/inttest/k8s.go

The intention of the test is to see if we can deploy an instance of a stack. It also tests that a groups encrypted k8s config can be decrypted and is used to deploy into that k8s cluster. It establishes what we need in terms of the test setup (gnomock/k8s client and encrypted config). I took the simplest stack we have `whoami-go`.
* setup k8s via k3s
* encrypt k8s config using age https://github.com/getsops/sops#22encrypting-using-age
* set SOPS_AGE_KEY env in test with the private key used to encrypt. The encrypted k8s config will contain the age details (recipient/public key) needed to decrypt it. `decryptYaml(configuration.KubernetesConfiguration)` will rely the env var to find the private key
* deploy whoami-go and assert the pod is ready i.e. healthy. I am watching pod events using …

test: add instance integration test

---

pkg/database/database_integration_test.go
pkg/database/docs.go
pkg/database/handler.go
pkg/instance/instance_integration_test.go
scripts/databases/seed.sh
scripts/databases/upload.sh
swagger/swagger.yaml

Implements an S3 folder-like structure with a `name` field that supports forward slashes. 
Can be tested at - https://radnov.im.dhis2.org
Note that leading and trailing `/` is trimmed from the prefix, so that users can't create paths like `this/one//file.sql.gz`, where the double forward slash `//` would result in an extra directory in S3 named `/`.
```
$ ./upload.sh whoami /path/with/leading/and/trailing/slash/ ~/Downloads/dhis2-dbs/dev.sql.gz | jq
######################################################################################################################################################################################## 100.0%
{
"id": 29,
"createdAt": "2023-10-12T10:17:25.607254559Z",
"updatedAt": "2023-10-12T10:17:25.607254559Z",
"name": "path/with/leading/and/trailing/slash", …
```

refactor: support S3 folder/path structure with an optional db prefix

---

internal/errdef/errdef.go
internal/middleware/errorHandler.go
pkg/instance/handler.go
pkg/instance/kubernetes.go
swagger/swagger.yaml

The goal of this PR is to avoid returning 500 when multiple pods are found during an instance status request

refactor: return conflict if multiple pods are found

---

pkg/instance/service.go
pkg/instance/service_test.go
stacks/pgadmin/helmfile.yaml

The goal of this PR is to...
* reject user submitted consumed parameters before resolving parameters from required instances
* avoid overlapping ingress paths

fix: deploy both core and pgAdmin

---

.env.example
.github/workflows/e2e.yaml
cmd/serve/main.go
helm/chart/templates/secret.yaml
helm/data/secrets/dev/values.yaml
helm/data/secrets/prod/values.yaml
pkg/config/config.go
pkg/group/group_integration_test.go
pkg/model/group.go
pkg/user/user_integration_test.go
pkg/user/util.go

Related to https://github.com/dhis2-sre/im-web-client/pull/352
This PR updates the e2e workflow to trigger the Playwright tests in the `im-web-client` repository, instead of using the `stack_tests.sh` script. The workflow will be triggered only if the `deploy` label is added and after the build-test-deploy workflow has completed, as we want to have the changes deployed before we trigger the e2e test in the `im-web-client` repository.
The PR also adds a default user, like the admin user we already have, that is added to the whoami group and will be used for testing.

ci: trigger im-web-client e2e tests workflow

---

scripts/instances/reset.sh

The goal of this PR is to update the reset user script to target deployment instances.
It no longer accepts group and name but rather the id of the deployment instance.
It can be used in combination with the findByName.sh script as seen below
```
./reset.sh $(./findByName.sh group name | jq '.instances[] | select(.stackName=="dhis2-core") | .id')
```

chore: update reset.sh to target deployment instances

---

pkg/model/database.go
pkg/model/instance.go

Gorm doesn't error or warn about indices of different tables that have the same name and only creates one of them.
The renamed indices are using the [format suggested here](https://stackoverflow.com/questions/4107915/postgresql-default-constraint-names/4108266#4108266) - `{tablename}_{columnname(s)}_{suffix}`.
Note that the rest of the indices will be renamed in a separate PR (https://dhis2.atlassian.net/browse/DEVOPS-378).

refactor: deduplicate index names

---

cmd/serve/main.go
go.mod
go.sum
internal/server/engine.go
pkg/inttest/http.go

Use middleware https://github.com/samber/slog-gin to let Gin log using slog. This means we replaced the default
https://github.com/gin-gonic/gin/blob/4ea0e648e38a63d6caff14100f5eab5c50912bcd/gin.go#L216-L221
by creating a new router and only adding the `Recovery` middleware and the slog middleware.
So instead of a log line like
```
[GIN] 2024/04/29 - 14:33:01 | 200 |     105.956µs |    10.0.103.193 | GET      "/health"
```
We now log
```
time=2024-04-29T14:33:01.009Z level=INFO msg="Incoming request" http.request.time=2024-04-29T14:33:01.008Z http.request.method=GET http.request.host=10.0.101.202:8080 http.request.path=/health http.request.query="" http.request.params=map[] http.request.route=/health http.request.ip=10.0.103.193 http.request.referer="" http.request.length=0 …
```

chore: let gin log using slog DEVOPS-170

---

cmd/serve/main.go
helm/chart/values.yaml
internal/log/hander_test.go
internal/log/handler.go
internal/middleware/authorization.go
internal/middleware/errorHandler.go
internal/server/engine.go
pkg/config/config.go
pkg/inttest/http.go
pkg/user/user_integration_test.go

* Set `GIN_MODE` to release. We need to make sure every im-manager log line uses the key=val format so we can parse it in Loki using logfmt. Gin prints some debug info and a warning in a non logfmt at the start of im-manager. Setting the mode to release stops this.
* Return `http.request.id` to users receiving an HTTP 500. The id is generated by https://github.com/samber/slog-gin and put into the Gin context. Once we have configured Loki to extract that id and index it we can find all logs to the users failed request.
* Do not log HTTP 500 errors in our error handler. The logging middleware for Gin will [already log errors](https://github.com/samber/slog-gin/blob/812b3ffb5d6c562fa79e00edaef5409cd053f4d0/middleware.go#L62) using `slog.Error`.
* Log `http.id` when in Gin context. …

chore: log request id inside Gin context DEVOPS-170

---

.golangci.yml
.pre-commit-config.yaml
cmd/serve/main.go
internal/middleware/authentication.go
pkg/config/config.go
pkg/database/database_integration_test.go
pkg/database/handler.go
pkg/database/service.go
pkg/instance/helmfile.go
pkg/instance/instance_integration_test.go
pkg/instance/service.go
pkg/instance/service_test.go
pkg/instance/ttlDestroyConsumer.go
pkg/instance/ttlDestroyConsumer_test.go
pkg/storage/s3.go
pkg/token/helper/tokenHelper.go
pkg/token/repository.go
pkg/token/service.go
pkg/user/user_integration_test.go

* replace all uses of log with slog.
* setup https://golangci-lint.run/usage/linters/#sloglint so we
* don't go back to the log package.
* don't use the default logger via slog.Info and the like. Doing that will likely log in a different format than what we configure in main.
* stick to the same key naming style.
* use static messages and put dynamic values into key/values.
* Configure Loki to extract and index some of the key/value pairs in our log lines. I am hoping that https://grafana.com/docs/loki/latest/send-data/promtail/stages/logfmt works since the TextHandler emits space separated `key=val` pairs. Extract at least `http.id` which is the request/trace id generated by the slog middleware at the start of a request.

chore: replace all uses of log with slog DEVOPS-170

---

internal/middleware/authorization.go
pkg/model/user.go

as described in https://pkg.go.dev/log/slog\#LogValuer. When we now log a user using slog it will only log the users id which should be enough for us to debug an issue. The id does not disclose any personal identifiable information as its an internal id that if we delete a user has no trace back to that person.

chore: let user implement LogValuer to hide secrets DEVOPS-389

---

cmd/serve/main.go
go.mod
go.sum
internal/log/hander_test.go
internal/log/handler.go
internal/middleware/authorization.go
internal/server/engine.go
pkg/group/handler.go
pkg/group/service.go
pkg/inttest/db.go
pkg/inttest/http.go
pkg/storage/postgresql.go
pkg/user/handler.go
pkg/user/handler_test.go
pkg/user/repository.go
pkg/user/service.go
pkg/user/user_integration_test.go
pkg/user/util.go
swagger/swagger.yaml

* let Gorm log using slog using https://github.com/orandin/slog-gorm which implements Gorms' Logger interface https://gorm.io/docs/logger.html#Customize-Logger
* we need to thread the `context.Context` through to Gorm if we want to log attributes from the context like the request `id`. Note that `gin.Context` implements `context.Context`
* remove slog groups so every log line produced with a Context gets attribute `id` with the request id.
I adjusted  `go test -v ./... -run "TestUserHandler/AsAdmin/DeleteUser"
` locally to use the same logging setup as in main.
Here is a sample output 
```
time=2024-05-03T17:01:06.118+02:00 level=INFO msg="SQL query executed [3.158881ms]" query="DELETE FROM \"users\" WHERE \"users\".\"id\" = 2" duration=3.158881ms rows=1 …
```

chore: let Gorm log using slog DEVOPS-391

---

.golangci.yml

enforce we are logging using `log/slog` instead of `log`
These are the errors you will get when you add a change using `log`
```
pkg/config/config.go:211:2: use of `log.Println` forbidden because "Use log/slog to log" (forbidigo)
log.Println("len(GROUP_NAMES) != len(GROUP_HOSTNAMES)")
^
```
Use of `log.Fatal` is a bad idea as it calls `os.Exit` under the hood. This means you will have multiple places in your app that can exit. That makes it harder to understand where our app can terminate. We should only call `os.Exit` in main. All other places should return an error. The error is then either handled as its recoverable/temporary or it is handed to main which exits.
```
pkg/config/config.go:211:2: use of `log.Fatalf` forbidden because "Only main should call os.Exit(). Return an error …
```

chore: ban logging using log via linter DEVOPS-170

---

Dockerfile
cmd/serve/main.go

The slog [TextHandler](https://pkg.go.dev/log/slog#TextHandler) we are using is separating groups by `.` which is invalid in Loki (as it takes a lot from prometheus).
https://grafana.com/docs/loki/latest/get-started/labels/#format
This means we currently get parsing errors when using [logfmt](https://grafana.com/docs/loki/latest/send-data/promtail/stages/logfmt/). We cannot extract labels/values from keys which are under a group. Examples are the response.status or response.latency. This limits our ability in searching and creating metrics.
Not using groups when logging is not a good option as
* we do not always control how a 3rd party logs
* we get context from a group like in `request.method`, `method` alone is very generic
We can pipe logs through `jq` if we want to only get the logs …

chore: log JSON so we can parse groups in Loki DEVOPS-396

---

pkg/user/user_integration_test.go

as our test run in parallel the get all test is racing against the others that are creating users
A `WaitGroup` uses an atomic internally but does not give us access to it. We therefore wrap a `WaitGroup` with an atomic for the count.

test: wait for users creation

---

.github/workflows/build-test-deploy.yaml
.gitignore
Dockerfile
Makefile
cmd/serve/main.go
docker-compose.yml
pkg/config/config.go
pkg/storage/redis.go

Fail when redis cannot be reached on startup as we do with other services.
Improve the RabbitMQ healthcheck so it is ready to take connections. We can now rely on Docker healthchecks and use a single docker compose up to start the smoke-test.
https://github.com/dhis2-sre/gha-workflows/pull/55
uses a retry with timeout so we do not need to sleep to guess and wait when IM is ready. Cleanup containers created during the smoke test.

chore: use single docker compose up

---

cmd/serve/main.go
internal/server/engine.go
pkg/inttest/http.go

A panic in Gins server.GetEngine was not visible to us when deploying. This lead IM to be stuck in a CrashLoopBackoff. This is an example of the panic
```sh
panic: bad origin: origins must contain '*' or include http://,https://
goroutine 1 [running]:
github.com/gin-contrib/cors.newCors({0x0, {0xc0005ed5c0, 0x3, 0x3}, 0x0, 0x0, {0xc00059a070, 0x7, 0x7}, 0x0, ...})
/go/pkg/mod/github.com/gin-contrib/cors@v1.7.2/config.go:44 +0x29c
github.com/gin-contrib/cors.New({0x0, {0xc0005ed5c0, 0x3, 0x3}, 0x0, 0x0, {0xc00059a070, 0x7, 0x7}, 0x0, ...})
/go/pkg/mod/github.com/gin-contrib/cors@v1.7.2/cors.go:194 +0x39
github.com/dhis2-sre/im-manager/internal/server.GetEngine(0xc000519050, {0xc00001405a, 0x1}, {0xc0005ed5c0, 0x3, 0x3})
/src/internal/server/engine.go:25 +0x525
main.run() …
```

chore: validate CORS config

---

go.mod
go.sum
internal/middleware/errorHandler.go

We originally used slogin but switched away from it due to some limitations. We forgot to get the request id from the context via our own function. It was thus not found in the context.

fix: return request ID on status 500

---

.golangci.yml
.pre-commit-config.yaml

like any other linter. This way it will be kept up to date. https://github.com/tekwizely/pre-commit-golang has no new releases. And we can disable linting issues in the same way as for other linters.
Proof that gosec is enabled after this change
```
golangci-lint linters
Enabled by your configuration linters:
errcheck: errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases [fast: false, auto-fix: false]
forbidigo: Forbids identifiers [fast: false, auto-fix: false]
gocritic: Provides diagnostics that check for bugs, performance and style issues. [fast: false, auto-fix: false]
gosec (gas): Inspects source code for security problems [fast: false, auto-fix: false]
gosimple (megacheck): Linter for Go source code that …
```

ci: use gosec via golangci-lint

---

.golangci.yml
.pre-commit-config.yaml
Makefile

[sloglint](https://github.com/go-simpler/sloglint?tab=readme-ov-file#context-only) [context-only=scope](https://github.com/go-simpler/sloglint?tab=readme-ov-file#context-only) ([v0.6.0](https://github.com/go-simpler/sloglint/releases/tag/v0.6.0)) detects function declarations with a `context.Context` as the first parameter in the scope of a logger call.
Our [slog handler](https://github.com/dhis2-sre/im-manager/blob/657a8b19d82e882b505c53ca0b524fa05231710a/internal/log/handler.go#L32) will add the request id and user to the log when its present in the context. For this to work we have to log using the context aware logger methods. This slog linter setting helps to remind us of that like so
```
pre-commit run golangci-lint --all-files --show-diff-on-failure …
```

chore: use sloglint context-only=scope DEVOPS-395

---

scripts/auth.sh

chore: fix/auth.sh

---

.github/workflows/build-test-deploy.yaml
skaffold.yaml

We have been bitten by this before
https://github.com/dhis2-sre/im-manager/pull/664
Skaffold changed its behavior. This is why changes to RabbitMQ in Skaffold did not trigger a deployment of RabbitMQ. Use the same setting for redis as well so we don't end up here again.

fix: let skaffold update rabbitmq and redis on change

---

README.md

The intent is to have a minimal step-by-step guide for starting a local development environment (albeit not fully functional).

docs: add local development environment section to README

---

helm/data/values/dev/postgresql.yaml
helm/data/values/dev/rabbitmq.yaml
helm/data/values/dev/redis.yaml
helm/data/values/prod/postgresql.yaml
helm/data/values/prod/rabbitmq.yaml
helm/data/values/prod/redis.yaml
helm/data/values/prod/values.yaml
skaffold.yaml

Added `nodeSelector` and `tolerations` config to all Helm releases in the Skaffold file, which means that all IM envs will get scheduled on the same dedicated IM node.
Related to https://github.com/dhis2-sre/im-web-client/pull/657

ci: add nodeSelector and tolerations for dedicated prod env node

---

go.mod
go.sum
helm/chart/templates/clusterrole.yaml
pkg/database/database_integration_test.go
pkg/instance/docs.go
pkg/instance/handler.go
pkg/instance/instance_integration_test.go
pkg/instance/repository.go
pkg/instance/router.go
pkg/instance/service.go
pkg/inttest/http.go
pkg/stack/stack.go
scripts/instances/update-deployment.sh
scripts/instances/update-dhis2-core.sh
scripts/instances/update-dhis2-db.sh
swagger/swagger.yaml

Updating the Deployment's `Name` and `Group` is not allowed. The name of a K8s object is immutable, so we need to destroy and re-create the Instance again anyway. Same goes for the group, if the current and new group have different Namespaces. With that in mind, we are not allowing changing the group, as it requires too much conditional logic that we should like to avoid.

refactor: add endpoints for updating deployment and deployment instance

---

pkg/database/repository.go
pkg/model/database.go
swagger/swagger.yaml

The reason for this PR is that when listing databases it'll be a better user experience if we can include who owns the lock and which instance it's associated with

feat: include User and Instance when retrieving the Lock

---

pkg/instance/repository.go
pkg/model/database.go
pkg/model/instance.go
swagger/swagger.yaml

I wanted to delete an instance but were getting a 500 error. It turned out the instance had a lock on it. How exactly we'd like to deal with this client side isn't clear but we'll certainly need to include the lock when listing instances

feat: include lock when listing deployments
